.TH "bug" 3 "Thu Nov 16 2017" "Servocontrol" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bug \- Bug List 

.IP "\fBGlobal \fBmatrix_rot_x\fP (matrix_t *m, double theta)\fP" 1c
Create x,y,z static rotation matrices to avoid alloc/free
.IP "\(bu" 2
The result must be deleted with \fBmatrix_del()\fP 
.PP
.PP

