.TH "linkage" 3 "Thu Nov 16 2017" "Servocontrol" \" -*- nroff -*-
.ad l
.nh
.SH NAME
linkage \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <servoctl\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBbase_x\fP"
.br
.ti -1c
.RI "\fBbase_y\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "base_x"

.SS "base_y"


.SH "Author"
.PP 
Generated automatically by Doxygen for Servocontrol from the source code\&.
