.TH "matrix" 3 "Tue Nov 14 2017" "Servocontrol" \" -*- nroff -*-
.ad l
.nh
.SH NAME
matrix \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <matrix\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBnrows\fP"
.br
.ti -1c
.RI "int \fBncols\fP"
.br
.ti -1c
.RI "double * \fBv\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "int ncols"

.SS "int nrows"

.SS "double* v"


.SH "Author"
.PP 
Generated automatically by Doxygen for Servocontrol from the source code\&.
